name: Build release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instala MinGW
        run: |
          sudo apt install mingw-w64

      - name: Compila SDL2 w64
        run: |
          mkdir -p /tmp/sdl2/src
          pushd /tmp/sdl2/src
          wget https://github.com/libsdl-org/SDL/releases/download/release-2.26.1/SDL2-devel-2.26.1-mingw.tar.gz
          tar -xvf SDL2-devel-2.26.1-mingw.tar.gz
          popd
          mkdir -p target/x86_64-pc-windows-gnu/release/deps
          cp -r /tmp/sdl2/src/SDL2-2.26.1/x86_64-w64-mingw32/lib/* target/x86_64-pc-windows-gnu/release/deps/

      - name: Instala SDL2 Linux
        run: |
          sudo apt install libsdl2-dev

      - name: Atualiza toolchain
        run: |
          rustup update
          rustup install nightly
          rustup target add x86_64-pc-windows-gnu

      - name: Compila release Windows
        run: |
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Compila release Linux
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Empacota release Windows
        run: |
          mkdir /tmp/release-windows
          cp -r target/x86_64-pc-windows-gnu/release/gauss.exe /tmp/release-windows/gauss.exe
          cp -r /tmp/sdl2/src/SDL2-2.26.1/x86_64-w64-mingw32/bin/SDL2.dll /tmp/release-windows/SDL2.dll
          cp -r res /tmp/release-windows/res

      - name: Empacota release Linux
        run: |
          mkdir /tmp/release-linux
          cp -r target/x86_64-unknown-linux-gnu/release/gauss /tmp/release-linux/gauss
          cp -r res /tmp/release-linux/res

      - name: Empacota release Windows
        uses: actions/upload-artifact@v3
        with:
          name: gauss-win64.zip
          path: /tmp/release-windows

      - name: Empacota release Linux
        uses: actions/upload-artifact@v3
        with:
          name: gauss-linux64.zip
          path: /tmp/release-linux

      - name: Cria release
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Prepara release Windows
        uses: actions/download-artifact@v3
        with:
          name: gauss-win64.zip

      - name: Prepara release Linux
        uses: actions/download-artifact@v3
        with:
          name: gauss-linux.zip

      - name: Sobe release Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: gauss-win64.zip
          asset_name: gauss-win64.zip
          asset_content_type: application/gzip

      - name: Sobe release Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: gauss-linux64.zip
          asset_name: gauss-linux64.zip
          asset_content_type: application/gzip
